version: "2"

linters:
  enable:
    - gosec
    - errcheck
    - govet
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/mattjoyce/framore
